/**
 * Build-time service-worker generator (SITE-11 / SW-334).
 *
 * Emits `public/sw.js` with a build-id-keyed precache manifest derived from the
 * ACTUAL content — no hardcoded route lists that drift:
 *   • routes  ← content/SUMMARY.md (same source the site navigation uses)
 *   • assets  ← image references found in the content markdown, plus the LED
 *               status GIFs and the PWA icons.
 *
 * The build id keys the cache names so a new deploy installs a fresh cache and
 * the `activate` handler deletes every older one — a stale docs cache is worse
 * than no cache (spec SITE-11). On Vercel the id is the deploy commit SHA
 * (unique per deploy); locally it falls back to a content hash.
 *
 * Runs from `predev` / `prebuild` AFTER setup.mjs has populated content/ and
 * public/gitbook-assets/.
 */
import {
  readFileSync,
  writeFileSync,
  existsSync,
  readdirSync,
} from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { createHash } from "crypto";

const __dirname = dirname(fileURLToPath(import.meta.url));
const docsRoot = join(__dirname, ".."); // docs-site/
const contentRoot = join(docsRoot, "content");
const assetsRoot = join(docsRoot, "public", "gitbook-assets");

// ── 1. Routes from SUMMARY.md ─────────────────────────────────
// Mirror lib/docs.ts filePathToHref: README → "/", drop .md, strip /README.
function filePathToHref(filePath) {
  let href = filePath.replace(/\.md$/, "");
  if (href === "README") return "/";
  href = href.replace(/\/README$/, "");
  return "/" + href;
}

function parseRoutes() {
  const summaryPath = join(contentRoot, "SUMMARY.md");
  if (!existsSync(summaryPath)) return ["/"];
  const lines = readFileSync(summaryPath, "utf-8").split("\n");
  const hrefs = new Set(["/"]);
  for (const line of lines) {
    const m = line.match(/^\s*\*\s+\[[^\]]+\]\(([^)]+)\)/);
    if (m) hrefs.add(filePathToHref(m[1].trim()));
  }
  return [...hrefs];
}

// ── 2. Critical assets from the content itself ────────────────
function toAssetUrl(ref) {
  const marker = ".gitbook/assets/";
  const i = ref.indexOf(marker);
  let name = i >= 0 ? ref.slice(i + marker.length) : ref;
  name = name.replace(/[)"'>\s]+$/, "").trim();
  try {
    name = decodeURIComponent(name);
  } catch {
    /* keep as-is if it isn't valid percent-encoding */
  }
  return "/gitbook-assets/" + name.split("/").map(encodeURIComponent).join("/");
}

const IMG_EXT = /\.(png|jpe?g|gif|svg|webp)$/i;

function walk(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

function collectAssets() {
  const assets = new Set();

  // (a) Image refs inside the markdown corpus (the single source of truth).
  if (existsSync(contentRoot)) {
    for (const file of walk(contentRoot)) {
      if (!file.endsWith(".md")) continue;
      const md = readFileSync(file, "utf-8");
      const refs = md.match(/\.gitbook\/assets\/[^)"'>\s]+/g) || [];
      for (const ref of refs) {
        const url = toAssetUrl(ref);
        if (IMG_EXT.test(url)) assets.add(url);
      }
    }
  }

  // (b) LED status animations — the field-critical visual language of the LED
  //     guide. All GIFs in the asset dir are indicator animations and are tiny.
  if (existsSync(assetsRoot)) {
    for (const name of readdirSync(assetsRoot)) {
      if (/\.gif$/i.test(name)) {
        assets.add("/gitbook-assets/" + name.split("/").map(encodeURIComponent).join("/"));
      }
    }
  }

  // (c) PWA + app-shell icons.
  for (const icon of ["/ocutrap-mark.png", "/icon-192.png", "/icon-512.png"]) {
    if (existsSync(join(docsRoot, "public", icon.replace(/^\//, "")))) assets.add(icon);
  }

  return [...assets].sort();
}

// ── 3. Build id ───────────────────────────────────────────────
function computeBuildId(routes, assets) {
  const sha = (process.env.VERCEL_GIT_COMMIT_SHA || "").slice(0, 12);
  if (sha) return sha;
  // Local / non-Vercel: hash the precache manifest + markdown bytes so the id
  // changes whenever published content changes.
  const hash = createHash("sha256");
  hash.update(JSON.stringify({ routes, assets }));
  if (existsSync(contentRoot)) {
    for (const file of walk(contentRoot)) {
      if (file.endsWith(".md")) hash.update(readFileSync(file));
    }
  }
  return hash.digest("hex").slice(0, 12);
}

// ── 4. Emit public/sw.js ──────────────────────────────────────
const routes = parseRoutes();
const assets = collectAssets();
const buildId = computeBuildId(routes, assets);

const sw = `/* AUTO-GENERATED by scripts/generate-sw.mjs — do not edit.
 * OcuTrap docs offline service worker (SITE-11 / SW-334).
 * Build id: ${buildId}  ·  routes: ${routes.length}  ·  assets: ${assets.length}
 */
const BUILD_ID = ${JSON.stringify(buildId)};
const PRECACHE = "ocutrap-docs-precache-" + BUILD_ID;
const RUNTIME = "ocutrap-docs-runtime-" + BUILD_ID;
const OFFLINE_URL = "/offline";

// App shell + the search index (so full-text search works offline) + every KB
// route + critical images. /api/* is otherwise network-only (see fetch below).
const PRECACHE_URLS = [
  "/",
  OFFLINE_URL,
  "/manifest.webmanifest",
  "/api/search",
  ${JSON.stringify(routes)}.filter(function (r) { return r !== "/"; }),
  ${JSON.stringify(assets)},
].flat();

// Media that must stay network-only (too large to precache); the poster image
// falls back through the normal image path.
function isVideo(pathname) {
  return /\\.(mp4|mov|webm|m4v|heic)$/i.test(pathname);
}

self.addEventListener("install", function (event) {
  event.waitUntil(
    (async function () {
      const cache = await caches.open(PRECACHE);
      // allSettled: one 404 asset must not abort the whole precache. cache:"reload"
      // bypasses the HTTP cache so we snapshot the freshly deployed bytes.
      await Promise.allSettled(
        PRECACHE_URLS.map(function (url) {
          return cache.add(new Request(url, { cache: "reload" }));
        })
      );
      await self.skipWaiting();
    })()
  );
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    (async function () {
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter(function (k) {
            return (
              k.indexOf("ocutrap-docs-") === 0 &&
              k !== PRECACHE &&
              k !== RUNTIME
            );
          })
          .map(function (k) {
            return caches.delete(k);
          })
      );
      await self.clients.claim();
    })()
  );
});

async function staleWhileRevalidate(request) {
  const cached = await caches.match(request);
  const network = fetch(request)
    .then(function (response) {
      if (response && response.ok) {
        caches.open(RUNTIME).then(function (c) {
          c.put(request, response.clone());
        });
      }
      return response;
    })
    .catch(function () {
      return null;
    });
  return cached || (await network) || Response.error();
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  try {
    const response = await fetch(request);
    if (response && response.ok) {
      const cache = await caches.open(RUNTIME);
      cache.put(request, response.clone());
    }
    return response;
  } catch (e) {
    return Response.error();
  }
}

// Navigations: serve cache immediately when we have it (stale-while-revalidate),
// otherwise go to network, and fall back to the offline page when both miss.
async function handleNavigation(request) {
  const cached = await caches.match(request);
  const network = fetch(request)
    .then(function (response) {
      if (response && response.ok) {
        caches.open(RUNTIME).then(function (c) {
          c.put(request, response.clone());
        });
      }
      return response;
    })
    .catch(function () {
      return null;
    });
  if (cached) return cached;
  const fresh = await network;
  if (fresh) return fresh;
  return (
    (await caches.match(OFFLINE_URL)) ||
    (await caches.match("/")) ||
    Response.error()
  );
}

self.addEventListener("fetch", function (event) {
  const request = event.request;
  if (request.method !== "GET") return;

  let url;
  try {
    url = new URL(request.url);
  } catch (e) {
    return;
  }
  // Only handle our own origin; cross-origin (fonts, PostHog, etc.) hits network.
  if (url.origin !== self.location.origin) return;

  // /api/* stays on the network so the AI ask reflects live state — EXCEPT the
  // search index, which we cache so full-text search works offline.
  if (url.pathname.indexOf("/api/") === 0) {
    if (url.pathname === "/api/search") {
      event.respondWith(staleWhileRevalidate(request));
    }
    return;
  }

  // Large media: network-only.
  if (isVideo(url.pathname)) return;

  // Document navigations.
  if (request.mode === "navigate") {
    event.respondWith(handleNavigation(request));
    return;
  }

  // Content-hashed Next assets are immutable → cache-first.
  if (url.pathname.indexOf("/_next/static/") === 0) {
    event.respondWith(cacheFirst(request));
    return;
  }

  // Everything else same-origin (images, icons, css) → stale-while-revalidate.
  event.respondWith(staleWhileRevalidate(request));
});

// Let the page trigger an immediate activation after an update.
self.addEventListener("message", function (event) {
  if (event.data === "SKIP_WAITING") self.skipWaiting();
});
`;

writeFileSync(join(docsRoot, "public", "sw.js"), sw);
console.log(
  `✓ Generated public/sw.js (build ${buildId}, ${routes.length} routes, ${assets.length} assets)`
);
